title: Antonio Nasi
description: Reflexões, textos e pesquisas
baseurl: ""
url: "https://antonionasi.com.br"
author: Antonio Nasi
email: contato@exemplo.com
lang: pt-BR

theme: null
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-sitemap

permalink: /:title/
